---
title: IDLE3 openen
hero_image: images/idle.png
description: Hoe IDLE3 te openen
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
steps:
  - 
    title: IDLE3 openen

