title: Opening IDLE3
hero_image: images/idle.png
description: How to open IDLE3
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
steps:
  - title: Opening IDLE3

