title: Opening IDLE3
hero_image: images/idle.png
description: How to open IDLE3
<<<<<<< HEAD
published: 'false'
steps:
  - title: Step one
    duration: 60
=======
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests:
technologies: "python"
steps:
  - title: Opening IDLE3
>>>>>>> draft
