---
title: IDLE3 खोलना
hero_image: images/idle.png
description: IDLE3 को कैसे खोलें
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
steps:
  - 
    title: IDLE3 खोलना

