---
title: Abriendo IDLE3
hero_image: images/idle.png
description: Cómo abrir IDLE3
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
steps:
  - 
    title: Abriendo IDLE3

