---
title: IDLE 실행하기
hero_image: images/idle.png
description: IDLE3을 실행하는 방법
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "python"
steps:
  - title: IDLE 실행하기

